// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/logingestion.proto

package logingestion

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for submitting a log
type SubmitLogRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Log content in raw format (required)
	LogContent string `protobuf:"bytes,1,opt,name=log_content,json=logContent,proto3" json:"log_content,omitempty"`
	// (Optional) Client-specified log hash, server will validate if provided
	ClientLogHash string `protobuf:"bytes,2,opt,name=client_log_hash,json=clientLogHash,proto3" json:"client_log_hash,omitempty"`
	// (Optional) Client-specified source organization ID, server will validate
	// permission if provided
	ClientSourceOrgId string `protobuf:"bytes,3,opt,name=client_source_org_id,json=clientSourceOrgId,proto3" json:"client_source_org_id,omitempty"`
	// (Optional) Client-specified original timestamp
	ClientTimestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=client_timestamp,json=clientTimestamp,proto3" json:"client_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubmitLogRequest) Reset() {
	*x = SubmitLogRequest{}
	mi := &file_proto_logingestion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitLogRequest) ProtoMessage() {}

func (x *SubmitLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logingestion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitLogRequest.ProtoReflect.Descriptor instead.
func (*SubmitLogRequest) Descriptor() ([]byte, []int) {
	return file_proto_logingestion_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitLogRequest) GetLogContent() string {
	if x != nil {
		return x.LogContent
	}
	return ""
}

func (x *SubmitLogRequest) GetClientLogHash() string {
	if x != nil {
		return x.ClientLogHash
	}
	return ""
}

func (x *SubmitLogRequest) GetClientSourceOrgId() string {
	if x != nil {
		return x.ClientSourceOrgId
	}
	return ""
}

func (x *SubmitLogRequest) GetClientTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ClientTimestamp
	}
	return nil
}

// Response message for log submission
type SubmitLogResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-generated unique request ID (UUID)
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Server-computed or validated log hash (SHA256)
	ServerLogHash string `protobuf:"bytes,2,opt,name=server_log_hash,json=serverLogHash,proto3" json:"server_log_hash,omitempty"`
	// Server-recorded received timestamp
	ServerReceivedTimestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=server_received_timestamp,json=serverReceivedTimestamp,proto3" json:"server_received_timestamp,omitempty"`
	// (Optional) Status information, e.g., "ACCEPTED"
	Status        string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitLogResponse) Reset() {
	*x = SubmitLogResponse{}
	mi := &file_proto_logingestion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitLogResponse) ProtoMessage() {}

func (x *SubmitLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logingestion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitLogResponse.ProtoReflect.Descriptor instead.
func (*SubmitLogResponse) Descriptor() ([]byte, []int) {
	return file_proto_logingestion_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitLogResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SubmitLogResponse) GetServerLogHash() string {
	if x != nil {
		return x.ServerLogHash
	}
	return ""
}

func (x *SubmitLogResponse) GetServerReceivedTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerReceivedTimestamp
	}
	return nil
}

func (x *SubmitLogResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_logingestion_proto protoreflect.FileDescriptor

const file_proto_logingestion_proto_rawDesc = "" +
	"\n" +
	"\x18proto/logingestion.proto\x12\flogingestion\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd3\x01\n" +
	"\x10SubmitLogRequest\x12\x1f\n" +
	"\vlog_content\x18\x01 \x01(\tR\n" +
	"logContent\x12&\n" +
	"\x0fclient_log_hash\x18\x02 \x01(\tR\rclientLogHash\x12/\n" +
	"\x14client_source_org_id\x18\x03 \x01(\tR\x11clientSourceOrgId\x12E\n" +
	"\x10client_timestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0fclientTimestamp\"\xca\x01\n" +
	"\x11SubmitLogResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12&\n" +
	"\x0fserver_log_hash\x18\x02 \x01(\tR\rserverLogHash\x12V\n" +
	"\x19server_received_timestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x17serverReceivedTimestamp\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status2\\\n" +
	"\fLogIngestion\x12L\n" +
	"\tSubmitLog\x12\x1e.logingestion.SubmitLogRequest\x1a\x1f.logingestion.SubmitLogResponseB\x19Z\x17tlng/proto/logingestionb\x06proto3"

var (
	file_proto_logingestion_proto_rawDescOnce sync.Once
	file_proto_logingestion_proto_rawDescData []byte
)

func file_proto_logingestion_proto_rawDescGZIP() []byte {
	file_proto_logingestion_proto_rawDescOnce.Do(func() {
		file_proto_logingestion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_logingestion_proto_rawDesc), len(file_proto_logingestion_proto_rawDesc)))
	})
	return file_proto_logingestion_proto_rawDescData
}

var file_proto_logingestion_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_logingestion_proto_goTypes = []any{
	(*SubmitLogRequest)(nil),      // 0: logingestion.SubmitLogRequest
	(*SubmitLogResponse)(nil),     // 1: logingestion.SubmitLogResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_proto_logingestion_proto_depIdxs = []int32{
	2, // 0: logingestion.SubmitLogRequest.client_timestamp:type_name -> google.protobuf.Timestamp
	2, // 1: logingestion.SubmitLogResponse.server_received_timestamp:type_name -> google.protobuf.Timestamp
	0, // 2: logingestion.LogIngestion.SubmitLog:input_type -> logingestion.SubmitLogRequest
	1, // 3: logingestion.LogIngestion.SubmitLog:output_type -> logingestion.SubmitLogResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_logingestion_proto_init() }
func file_proto_logingestion_proto_init() {
	if File_proto_logingestion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_logingestion_proto_rawDesc), len(file_proto_logingestion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_logingestion_proto_goTypes,
		DependencyIndexes: file_proto_logingestion_proto_depIdxs,
		MessageInfos:      file_proto_logingestion_proto_msgTypes,
	}.Build()
	File_proto_logingestion_proto = out.File
	file_proto_logingestion_proto_goTypes = nil
	file_proto_logingestion_proto_depIdxs = nil
}
