// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/logingestion.proto

package logingestion

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogIngestion_SubmitLog_FullMethodName = "/logingestion.LogIngestion/SubmitLog"
)

// LogIngestionClient is the client API for LogIngestion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LogIngestion service definition
type LogIngestionClient interface {
	// SubmitLog method for submitting a single log entry, supports HTTP POST
	SubmitLog(ctx context.Context, in *SubmitLogRequest, opts ...grpc.CallOption) (*SubmitLogResponse, error)
}

type logIngestionClient struct {
	cc grpc.ClientConnInterface
}

func NewLogIngestionClient(cc grpc.ClientConnInterface) LogIngestionClient {
	return &logIngestionClient{cc}
}

func (c *logIngestionClient) SubmitLog(ctx context.Context, in *SubmitLogRequest, opts ...grpc.CallOption) (*SubmitLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitLogResponse)
	err := c.cc.Invoke(ctx, LogIngestion_SubmitLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogIngestionServer is the server API for LogIngestion service.
// All implementations must embed UnimplementedLogIngestionServer
// for forward compatibility.
//
// LogIngestion service definition
type LogIngestionServer interface {
	// SubmitLog method for submitting a single log entry, supports HTTP POST
	SubmitLog(context.Context, *SubmitLogRequest) (*SubmitLogResponse, error)
	mustEmbedUnimplementedLogIngestionServer()
}

// UnimplementedLogIngestionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogIngestionServer struct{}

func (UnimplementedLogIngestionServer) SubmitLog(context.Context, *SubmitLogRequest) (*SubmitLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitLog not implemented")
}
func (UnimplementedLogIngestionServer) mustEmbedUnimplementedLogIngestionServer() {}
func (UnimplementedLogIngestionServer) testEmbeddedByValue()                      {}

// UnsafeLogIngestionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogIngestionServer will
// result in compilation errors.
type UnsafeLogIngestionServer interface {
	mustEmbedUnimplementedLogIngestionServer()
}

func RegisterLogIngestionServer(s grpc.ServiceRegistrar, srv LogIngestionServer) {
	// If the following call pancis, it indicates UnimplementedLogIngestionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogIngestion_ServiceDesc, srv)
}

func _LogIngestion_SubmitLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogIngestionServer).SubmitLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogIngestion_SubmitLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogIngestionServer).SubmitLog(ctx, req.(*SubmitLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LogIngestion_ServiceDesc is the grpc.ServiceDesc for LogIngestion service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogIngestion_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logingestion.LogIngestion",
	HandlerType: (*LogIngestionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitLog",
			Handler:    _LogIngestion_SubmitLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/logingestion.proto",
}
